### ISSUE TITLE
Managing objects - block text 

### ISSUE THREAD

**Issue by joncav** [OP5-Employee/OP5-Documentation#54]
01-06-06-Managing_objects_md.pdf
block text issue

**Comment by jollyrogue** [comment]
Should be fixed in tomorrows PDF release.

**Comment by ediedrich** [comment]
Still an issue on page 29 on single PDFs from 7/22. @jollyrogue

**Comment by jollyrogue** [comment]
@ediedrich This should be fixed in the 7-27 single PDFs.
